### ISSUE TITLE
2 BMS with 2 ESP32

### ISSUE THREAD

**Issue by Sjirka83** [syssi/esphome-jbd-bms#102]
Hello,

 

I have 2 JBD BMS. First I just connected a BMS with the ESP32-ble.yaml version and transferred the data to Homeassistant/ESPHome. This works perfectly. Now I wanted to connect the 2nd BMS in the same way with an additional ESP32 module. After starting the program, a connection to the BMS is only briefly established in the log and then the ESP can no longer be connected to the second battery.

 

I also tested the mutiple ble example.yaml, but only one BMS is connected there too. If I remove one ESP and restart the other, it connects to the 2nd battery.

 

What can I do to make each ESP32 connect to the BMS and deliver the data from both?

Thanks for the great project

**Comment by syssi** [comment]
Are you sure you are using a different MAC address per YAML configuration / per BMS? Could you provide both YAML configurations?
