### ISSUE TITLE
rs485 to d1 mini

### ISSUE THREAD

**Issue by IvanSerevko** [syssi/esphome-jbd-bms#105]
Hello, is it possible to connect this not via UART, but via RS485? I tried to configure it for different pins and do not receive data (I connected both GPIO4,GPIO5 and via RX,TX, I have the following model JBD-AP21S001 200A)

![зображення](https://github.com/user-attachments/assets/5d70677e-e3c4-488e-b30b-ee71f26a1b6d)

**Comment by syssi** [comment]
It depends on your hardware. What kind of signal is available at the RX/TX pins of your BMS?

**Comment by IvanSerevko** [comment]
![зображення](https://github.com/user-attachments/assets/f0dffd90-284e-474d-bd7d-218a7af3c50f)
also tried through
![зображення](https://github.com/user-attachments/assets/915cca90-2c12-42e0-9b62-8c66400c6fef)
and shows the data on the computer
![зображення](https://github.com/user-attachments/assets/6b2a6186-71ab-4559-b0b4-330e00a22b41)
and near the rs485 pin there are also 5v and gnd from which the wemos d1 mini was powered

**Comment by syssi** [comment]
Could you provide a macro/high resolution photo of the USB-to-RS485 converter module? If we are able to identify a RS485 converter here we are sure a RS485 converter is required between the ESP and the BMS.

**Comment by IvanSerevko** [comment]
![IMG_1510](https://github.com/user-attachments/assets/3381b6f2-8025-44c1-8def-e5e17a49e4dd)

**Comment by syssi** [comment]
Okay, this is a RS485 signal for sure. You have to attach a RS485 converter module to your ESP to interface the BMS. You should use one with automatic flow control like this:

![rs485](https://github.com/user-attachments/assets/b23f8c0a-3c5c-4b2c-a1ab-bd92ded51e38)

**Comment by IvanSerevko** [comment]
Thank you very much, I will try it and let you know if it worked

**Comment by IvanSerevko** [comment]
everything works great, thanks a lot, next task will be how to combine it with Solar2Mqqt)

**Comment by syssi** [comment]
Which BMS model do you own? I would like to extend the list of supported devices if possible.
