### ISSUE TITLE
Error compiling BLE version

### ISSUE THREAD

**Issue by Magsybaby** [syssi/esphome-jbd-bms#13]
Having some issues with ESPHome 2022.10 in Hass on x86

ESP32 UART version is fine but the BLE version fails to compile, I am not amending the provided yaml at all.

Help greatly appreciated :)

[logs_test_compile.txt](https://github.com/syssi/esphome-jbd-bms/files/9845140/logs_test_compile.txt)

**Comment by syssi** [comment]
I've pushed a fix: https://github.com/syssi/esphome-jbd-bms/commit/421e4988196a92bf065b2bb4824b253025a32a1e

Please download the BLE example YAML again and give it another try!

**Comment by Magsybaby** [comment]
Brilliant, thank you for the work in the fix and the integration! :)
