### ISSUE TITLE
Way to reduce update interval

### ISSUE THREAD

**Issue by Paxy** [syssi/esphome-jbd-bms#22]
First of all, great job. I can also confirm that the project is working with JBD-SP04S020-L4S-120A-B-U-K.
Is there any way to increase the update interval (less frequent) when used with HA API?
Parameters like _rx_timeout_ or _refresh_ in _external_components_ do not reduce the update interval.

**Comment by syssi** [comment]
```
jbd_bms:
  rx_timeout: ${rx_timeout}
  update_interval: 30s
```

is what you are looking for! :-)

**Comment by Paxy** [comment]
Yeah, that's it. I have tried that in the wrong place. 
Maybe you can add it in sample confs.
Tnx again.

**Comment by syssi** [comment]
I've improved the examples. Have fun!
