### ISSUE TITLE
bluetooth connection?

### ISSUE THREAD

**Issue by mager33** [syssi/esphome-jbd-bms#28]
Hi, does this work with a serial connection via bluetooth?

**Comment by syssi** [comment]
This implementation supports both. A serial connection and communication via bluetooth.

**Comment by syssi** [comment]
Does this answer your question?

**Comment by mager33** [comment]
Yes, thank you! (unfortunately, I've discovered that my battery pack from BASEN does not contain a JDB BMS but a VIP BMS; and ther is not much available for that)

**Comment by syssi** [comment]
@mager33 I would like to give it a try to talk to your BMS. Do you have some spare time for doing some testing and experiments?

**Comment by mager33** [comment]
Hi Sebastian, yes, of course. But I won't be available until 22.2.23. Best, Martin
 

Gesendet: Mittwoch, 15. Februar 2023 um 21:38 Uhr
Von: "Sebastian Muszynski" ***@***.***>
An: "syssi/esphome-jbd-bms" ***@***.***>
Cc: "Martin" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [syssi/esphome-jbd-bms] bluetooth connection? (Issue #28)


 

@mager33 I would like to give it a try to talk to your BMS. Do you have some spare time for doing some testing and experiments?

**Comment by syssi** [comment]
@mager33 To close the loop: We talked already on Reddit and you did provide the capture. :-P
