### ISSUE TITLE
Overkill JBD-SP25S003-L16S-100A-100A-B support

### ISSUE THREAD

**Issue by Uksa007** [syssi/esphome-jbd-bms#31]
Hi,

I have your code working with the Device model: JBD-SP25S003-L16S-100A-100A-B
It works pretty well, still testing but so far so good.

Will provide some more info once I'm happy for you to add it to your supported list.

**Comment by syssi** [comment]
That's for your feedback! How did you fix your temperature sensors?

**Comment by syssi** [comment]
I've extended the list of supported devices! Feel free to create additional issues if you miss a feature or something doesn't work as expected.
