### ISSUE TITLE
Add JBD-UP16S010-L16S-100A support

### ISSUE THREAD

**Issue by mykolavorobiov** [syssi/esphome-jbd-bms#60]
Could you help with new bms (Model Number UP16S010)
I see that esp host send 
![image](https://github.com/syssi/esphome-jbd-bms/assets/38053194/9b164b8a-69c4-4327-93f4-bcf2bae1f41f)
And has no response
But on protocol description I see that I should send ```DD 00 A5 03 00 FF 58 77```
![image](https://github.com/syssi/esphome-jbd-bms/assets/38053194/fed79ee0-84f4-4ae9-99c4-0e701682dce4)

Is it possible at all?

Esp32 connected via UART (lcd port)

**Comment by syssi** [comment]
Are you still willing to test your protocol flavor? I would provide a first attempt.

**Comment by mykolavorobiov** [comment]
Sorry for my late, I think that it was a problem with my hardware, coz I'm using MAX485 UART-RS485 without automatic flow control pin.
I [forked your repo](https://github.com/mykolavorobiov/esphome-jbd-bms-with-flow-pin) and make several changes to add flow pin.
It works correct for on my side now.

**Comment by mykolavorobiov** [comment]
Sorry for my late, I think that it was a problem with my hardware, coz I'm using MAX485 UART-RS485 without automatic flow control pin.
I [forked your repo](https://github.com/mykolavorobiov/esphome-jbd-bms-with-flow-pin) and make several changes to add flow pin.
It works correct for on my side now.
