### ISSUE TITLE
SP17S005

### ISSUE THREAD

**Issue by OM-3kChcBjgFR2COfP** [syssi/esphome-jbd-bms#80]
Hi, what about SP17S005?

**Comment by syssi** [comment]
I don't know. Please give it a try!

**Comment by OM-3kChcBjgFR2COfP** [comment]
i start trying, already build firmware for esp32, now trying wire dms and esp, l'll answer to you later, thnks

**Comment by syssi** [comment]
Let's close this issue for now. Feel free to re-open the issue if you made some progress! :-)
